### ISSUE TITLE
Pass current route to <body> class

### ISSUE THREAD

**Issue by chrisburnell** [codezeus/django-react-blog#13]
It is a handy technique in CSS to have a class on your top-most element, usually the `body` element, for making stylistic deviations from the norm on specific sections or pages of the site.

*For example:*

```html
<body class="page-about">

<h2 class="page-introduction">Lorem ipsum</h2>
```

```scss
.page-introduction {
    font-size: 2em;
    line-height: 1.5;
    .page-about & {
        font-size: 3em;
    }
}
```

*would come from* [/src/static/js/router.js](https://github.com/codezeus/django-react-blog/blob/master/src/static/js/router.js#L20).

---

The benefit of this technique over listening for and catching the route server-side (and creating a class to `@extend .page-introduction` is a leaner, simpler backend because the deviations and different cases are managed in the CSS, which is designed to handle situations like this well.

---

*Alternative #1:*

```html
<body>

<h2 class="page-introduction  page-introduction--about">Lorem ipsum</h2>
```

```scss
.page-introduction {
    font-size: 2em;
    line-height: 1.5;
}
.page-introduction--about {
    font-size: 3em;
}
```

This is one method for extending/modifying a class. The problem with this technique is that there's no inherent relationship between `.page-introduction` and `.page-introduction--about`. It helps that they would appear side-by-side in the CSS, but this isn't robust enough.

---

*Alternative #2:*

```html
<body>

<h2 class="page-introduction--about">Lorem ipsum</h2>
```

```scss
.page-introduction {
    font-size: 2em;
    line-height: 1.5;
}
.page-introduction--about {
    @extend .page-introduction;
    font-size: 3em;
}
```

Although this technique does create a relationship between `.page-introduction` and `.page-introduction--about`, we're still treading on unstable ground due to the opinionated nature of extending—which technique do we use? Which technique do we prefer? Which technique will we prefer in a year's time?

---

*Conclusion:*

It's easier for both the backend code and the CSS if the stylistic toggle is handled by a `body` class and managed in the CSS. The greatest advantage here probably has nothing to do with the front-end, but has to do with a simpler backend output scheme.
